import { ThumbsDown, ThumbsUp } from 'lucide-react';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Posts page",
  description: "Generated by create next app",
};

interface IPost {
  id: number;
  title: string;
  body: string;
  reactions: {
    likes: number;
    dislikes: number;
  };
  tags: string[];
}

const Home = async () => {
  const res = await fetch("https://dummyjson.com/posts", { cache: "force-cache" });
  const posts = await res.json();
  return (
    <div className="bg-gray-100 min-h-screen py-10 px-4">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-4xl font-bold text-center text-gray-900 mb-10">
          Posts
        </h1>

        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {posts?.posts?.map((post: IPost) => (
            <div
              key={post.id}
              className="bg-white border border-gray-200 rounded-xl shadow-sm p-6 hover:shadow-md transition-shadow"
            >
              <h2 className="text-2xl font-semibold text-gray-800 mb-3">
                {post.title}
              </h2>

              <p className="text-gray-600 text-sm leading-relaxed mb-4 line-clamp-4">
                {post.body}
              </p>

              <div className="flex gap-4 text-sm text-gray-600">
                <div className="flex items-center gap-1">
                  <ThumbsUp className="w-4 h-4" />
                  <span>{post.reactions.likes}</span>
                </div>
                <div className="flex items-center gap-1">
                  <ThumbsDown className="w-4 h-4" />
                  <span>{post.reactions.dislikes}</span>
                </div>
              </div>

              <div className="flex flex-wrap gap-2 mt-2">
                {post.tags.map((tag, i) => (
                  <span
                    key={i}
                    className="bg-gray-200 text-gray-700 text-xs px-2 py-1 rounded-full"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Home;
