import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Users page",
  description: "Generated by create next app",
};

const User = async () => {
  const res = await fetch("https://dummyjson.com/users", { cache: "force-cache" });
  const users = await res.json();

  return (
    <>
       <div className="mt-8">
        <h1 className="text-4xl font-bold text-center text-gray-900 mb-8">
          Users
        </h1>
      </div>
    
    <div className="max-w-6xl mx-auto p-6 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
      {users?.users?.map((user: any) => (
        <div
          key={user.id}
          className="flex items-center gap-4 border border-gray-200 rounded-lg p-4"
        >
          <img
            src={user.image}
            alt={user.firstName}
            className="w-14 h-14 rounded-full object-cover"
          />
          <div className="flex flex-col">
            <span className="font-semibold text-base">
              {user.firstName} {user.lastName}
            </span>
            <span className="text-sm">{user.email}</span>
            <span className="text-sm text-gray-600">{user.phone}</span>
          </div>
        </div>
      ))}
    </div>
    </>
  );
};

export default User;
