import Userr from '@/components/Userr';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Users page",
  description: "Generated by create next app",
};

const User = async () => {
  const res = await fetch("https://dummyjson.com/users", { cache: "force-cache" });
  const users = await res.json();

  return (
    <>
       <div className="mt-8">
        <h1 className="text-4xl font-bold text-center text-gray-900 mb-8">
          Users
        </h1>
      </div>
    
  <Userr users={users}/>
    </>
  );
};

export default User;
