import Food from "@/components/Food";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Recipes page",
  description: "Generated by create next app",
};

const Lorem = async () => {
  const data = await fetch("https://dummyjson.com/recipes", {cache: "force-cache"});
  const recipes = await data.json();

  return <div><Food data={recipes}/></div>;
};

export default Lorem;