import Post from '@/components/Post';
import { ThumbsDown, ThumbsUp } from 'lucide-react';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Posts page",
  description: "Generated by create next app",
};

const Home = async () => {
  const res = await fetch("https://dummyjson.com/posts", { cache: "force-cache" });
  const posts = await res.json();
  return (
    <div className="bg-gray-100 min-h-screen py-10 px-4">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-4xl font-bold text-center text-gray-900 mb-10">
          Posts
        </h1>

        <Post posts={posts}/>
      </div>
    </div>
  );
};

export default Home;
